name: Docker Build and Push

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build . -t ghcr.io/zeuswpi/haldis_een_prijsje:pr-${{ github.sha }}
          if [ "${{ github.event_name }}" == "push" ]; then
            docker tag ghcr.io/zeuswpi/haldis_een_prijsje:pr-${{ github.sha }} ghcr.io/zeuswpi/haldis_een_prijsje:latest
          fi

      - name: Push Docker image
        if: github.event_name == 'push'
        run: docker push --all-tags ghcr.io/zeuswpi/haldis_een_prijsje
